version: '3.5'

services:
  web_app:
    build: .
    image: app
    container_name: app
    hostname: app
    environment:
      CHECK_METHOD: ${METHOD}
      RUN_BENCHMARKS: ${BENCHMARKS}
      FASTTEXT_MODEL: ${FASTTEXT_MODEL}
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    networks:
      - esnet
networks:
  esnet: